pumped java version to 8 and added gradle install instructions

diff --git a/wercker-box.yml b/wercker-box.yml
--- a/wercker-box.yml
+++ b/wercker-box.yml
@@ -1,10 +1,9 @@
-name: java7-oracle
-version: 0.0.5
-description: Java7 box provisioned with the Oracle distribution via the webupd8team ppa. Comes with maven, ant and sbt
+name: java8-oracle
+version: 0.0.1
+description: Java8 box provisioned with the Oracle distribution via the webupd8team ppa. Comes with maven, ant and gradle 
 keywords:
   - java
   - ant
-  - sbt
   - maven
   - oracle
 type: main
@@ -13,26 +12,22 @@ env:
   SBT_OPTS: -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M
   IVY_CACHE_DIR: '"$WERCKER_CACHE_DIR/ivy"'
 script: |-
-  # Install Java7
+  # Install Java 8 
   sudo apt-get update
   sudo apt-get install python-software-properties curl wget -y
   sudo add-apt-repository ppa:webupd8team/java -y
   sudo apt-get update
-  echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
-  echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
-  sudo apt-get install oracle-java7-installer -qq
-
-  # Install sbt
-  wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.3/sbt-launch.jar
-  printf 'java -Dsbt.ivy.home=${IVY_CACHE_DIR} -Xmx512M ${SBT_OPTS} -jar `dirname $0`/sbt-launch.jar "$@"' > sbt
-  sudo chmod +x ./sbt
-  sudo mv sbt /usr/share/sbt
-  sudo mv sbt-launch.jar /usr/share/sbt-launch.jar
-  sudo ln -s /usr/share/sbt /usr/bin/sbt
-  sudo ln -s /usr/share/sbt-launch.jar /usr/bin/sbt-launch.jar
+  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
+  sudo apt-get install oracle-java8-installer -qq
+  sudo apt-get install oracle-java8-set-default -y
 
   # Install maven
   sudo apt-get install maven
+
+  # Install Gradle
+  sudo add-apt-repository ppa:cwchien/gradle -y
+  sudo apt-get update
+  sudo apt-get install gradle -y
 
   # Install ant
   sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
@@ -41,3 +36,4 @@ script: |-
    # We should have ant and ivy available
   type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
   type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
+  type gradle || { echo "No gradle command found...aborting"; exit 1; }
